name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use the latest LTS version
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Verify API Keys
      env:
        VITE_TMDB_API_KEY: ${{ secrets.VITE_TMDB_API_KEY }}
        VITE_GOOGLE_BOOKS_API_KEY: ${{ secrets.VITE_GOOGLE_BOOKS_API_KEY }}
      run: |
        echo "Checking API Keys..."
        if [ -z "$VITE_TMDB_API_KEY" ]; then echo "❌ VITE_TMDB_API_KEY is missing!"; exit 1; fi
        if [ -z "$VITE_GOOGLE_BOOKS_API_KEY" ]; then echo "❌ VITE_GOOGLE_BOOKS_API_KEY is missing!"; exit 1; fi
        echo "✅ API keys are set."

    - name: Build the project
      env:
        VITE_TMDB_API_KEY: ${{ secrets.VITE_TMDB_API_KEY }}
        VITE_GOOGLE_BOOKS_API_KEY: ${{ secrets.VITE_GOOGLE_BOOKS_API_KEY }}
      run: |
        echo "Building the project..."
        npm run build
        echo "Build completed successfully."

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages # Deploy to GitHub Pages branch
        folder: dist # Vite output directory
